name: minelabeler
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - pip
  - gdal
  - libarchive=3.8.7
  - libcurl=8.20.0
  - libsqlite=3.53.2
  - libxml2=2.15.3
  - libxml2-16=2.15.3
  - libxml2-devel=2.15.3
  - minizip=4.2.1
  - pandas
  - openpyxl
  - folium
  - branca
  - jinja2
  - pip:
      - PyQt6==6.11.0
      - PyQt6-Qt6==6.11.1
      - PyQt6-sip==13.11.1
      - PyQt6-WebEngine==6.11.0
      - PyQt6-WebEngine-Qt6==6.11.1
